inherit_from: configs/pointcloud/building.yaml
training:
  model_file: out/pointcloud/building/model.pt
  out_dir:  out/pointcloud/building
  batch_size: 65
  model_selection_metric: iou
  model_selection_mode: maximize
  checkpoint_every: 250
  visualize_every: 1000
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
